version: '3.3'
services:
    db:
        container_name: bedelia-db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: bedelia
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        volumes:
            - ./docker-database:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        container_name: bedelia-phpmyadmin
        depends_on:
            - db
        ports:
            - 8080:80











